name: Flutter CI

on:
  pull_request:
  push:
    branches: [ dev ]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4


      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true


      - name: Install dependencies
        run: flutter pub get


      - name: Analyze code
        run: flutter analyze || true


      - name: Run tests
        run: flutter test


      - name: Build Android APK
        run: flutter build apk --release


      - name: Install Apple Certificate
        uses: apple-actions/import-codesign-certs@v2
        with:
          p12-file-base64: ${{ secrets.IOS_CERTIFICATE_BASE64 }}
          p12-password: ${{ secrets.IOS_CERTIFICATE_PASSWORD }}


      - name: Install Provisioning Profile
        run: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          echo "${{ secrets.IOS_PROVISION_PROFILE_BASE64 }}" | base64 --decode > ~/Library/MobileDevice/Provisioning\ Profiles/profile.mobileprovision


      - name: Build iOS IPA
        run: flutter build ipa --release


      - name: Upload Android APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: build/app/outputs/flutter-apk/app-release.apk


      - name: Upload iOS IPA
        uses: actions/upload-artifact@v4
        with:
          name: ios-ipa
          path: build/ios/ipa/*.ipa
